naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][_A-Za-z0-9]*"

exceptions:
  TooGenericExceptionCaught:
    ignoreAnnotated:
      - "LintIgnoreTooGenericExceptionCaught"
  TooGenericExceptionThrown:
    ignoreAnnotated:
      - "LintIgnoreTooGenericExceptionThrown"
      - "LintIgnoreTooGenericExceptionThrown"

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated:
      - "Preview"
  UnusedPrivateFunction:
    ignoreAnnotated:
      - "Preview"
      - "PreviewSource"
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: false

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - "PreviewSource"
  TooManyFunctions:
    ignoreAnnotated:
      - "Preview"
      - "PreviewSource"
      - "LintIgnoreTooManyFunctions"
  LongMethod:
    ignoreAnnotated:
      - "Composable"
      - "Preview"
      - "PreviewSource"
      - "LintIgnoreLongMethod"